# Tema remoto
remote_theme: just-the-docs/just-the-docs

# Informazioni generali
author: Marco Marino
description: Raccolta di appunti universitari curati nei minimi dettagli
title: 📚📚

# Color scheme personalizzato (creato da te)
color_scheme: mio_schema

# CSS personalizzato (opzionale, ma utile per aggiustamenti)
just_the_docs:
  custom_css:
    - assets/css/override.css
  custom_head: _includes/head_custom.html

materie_order:
  - Algebra
  - Teoria dei segnali
  - Elettrotecnica
  - Elettronica
