remote_theme: just-the-docs/just-the-docs
color_scheme: light
author: Marco Marino
description: Raccolta di appunti universitari curati nei minimi dettagli

just_the_docs:
  custom_css:
    - "/assets/css/override.css"
